pipline{
    agent any
    stages{
        stage("Build")
        step{
            echo "Start Building"
            sh "npm install"
            sh "npmgit add .
            git run build"
            echo "Building Completed"
        }
    }
}